services:
  postgres:
    image: postgres:17
    container_name: queue-lab-postgres
    environment:
      POSTGRES_DB: queue_lab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d queue_lab"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: